---
- name: Locked vxod to root
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Disable useDNS
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?UseDNS'
    line: 'UseDNS no'

- name: RESTART SSH
  service:
    name: ssh
    state: restarted
  notify: Restart SSH
