---
- name: add repo for bullseye
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main"
    state: present

- name: import key
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: update cache after add repo
  apt:
    update_cache: yes

- name: install PSQL16 and Client
  apt:
    name:
      - postgresql-16
      - postgresql-client-16
    state: present

- name: nastroyka postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/16/main/postgresql.conf"
  notify: Restart PSQL

- name: nastroyka pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/16/main/pg_hba.conf"
  notify: Restart PSQL

- name: on PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes
